# Generated by Django 3.2.15 on 2022-08-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_num', models.IntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('place', models.CharField(blank=True, default='', max_length=100)),
                ('admn_year', models.IntegerField()),
            ],
        ),
    ]
